// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class AtomicCard
    {
        public string? Id { get; set; }
        public string? Artist { get; set; }
        public ICollection<string>? ColorIdentity { get; set; }
        public ICollection<string>? ColorIndicator { get; set; }
        public ICollection<string>? Colors { get; set; }
        public decimal? ConvertedManaCost { get; set; }
        public decimal? EdhrecRank { get; set; }
        public decimal? FaceConvertedManaCost { get; set; }
        public string? FaceName { get; set; }
        public ICollection<ForeignData>? ForeignData { get; set; }
        public string? Hand { get; set; }
        public bool? HasAlternativeDeckLimit { get; set; }
        public bool? IsReserved { get; set; }
        public string? Layout { get; set; }
        public LeadershipSkills? LeadershipSkills { get; set; }
        public Legalities? Legalities { get; set; }
        public string? Life { get; set; }
        public string? Loyalty { get; set; }
        public string? ManaCost { get; set; }
        public string? Name { get; set; }
        public string? Power { get; set; }
        public ICollection<string>? Printings { get; set; }
        public PurchaseUrls? PurchaseUrls { get; set; }
        public ICollection<Rulings>? Rulings { get; set; }
        public string? Side { get; set; }
        public ICollection<string>? SubTypes { get; set; }
        public ICollection<string>? SuperTypes { get; set; }
        public string? Text { get; set; }
        public string? Toughness { get; set; }
        public string? Type { get; set; }
        public ICollection<string>? Types { get; set; }
        public string? Uuid { get; set; }
    }
}
