// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class Card
    {
        public string? Uuid { get; set; }
        public string? Artist { get; set; }
        public string? AsciiName { get; set; }
        public ICollection<string>? Availability { get; set; }
        public string? BorderColor { get; set; }
        public ICollection<string>? ColorIdentity { get; set; }
        public ICollection<string>? ColorIndicator { get; set; }
        public ICollection<string>? Colors { get; set; }
        public decimal? ConvertedManaCost { get; set; }
        public decimal? Count { get; set; }
        public string? DuelDeck { get; set; }
        public decimal? EdhrecRank { get; set; }
        public decimal? FaceConvertedManaCost { get; set; }
        public string? FaceName { get; set; }
        public string? FlavorName { get; set; }
        public string? FlavorText { get; set; }
        public ICollection<ForeignData>? ForeignData { get; set; }
        public ICollection<string>? FrameEffects { get; set; }
        public string? FrameVersion { get; set; }
        public string? Hand { get; set; }
        public bool? HasContentWarning { get; set; }
        public bool? HasFoil { get; set; }
        public bool? HasAlternativeDeckLimit { get; set; }
        public bool? HasNonFoil { get; set; }
        public Identifier? Identifiers { get; set; }
        public bool? IsAlternative { get; set; }
        public bool? IsFoil { get; set; }
        public bool? IsFullArt { get; set; }
        public bool? IsOnlineOnly { get; set; }
        public bool? IsOversized { get; set; }
        public bool? IsPromo { get; set; }
        public bool? IsReprint { get; set; }
        public bool? IsReserved { get; set; }
        public bool? IsStarter { get; set; }
        public bool? IsStorySpotlight { get; set; }
        public bool? IsTextless { get; set; }
        public bool? IsTimeshifted { get; set; }
        public ICollection<string>? Keywords { get; set; }
        public string? Layout { get; set; }
        public LeadershipSkills? LeadershipSkills { get; set; }
        public Legalities? Legalities { get; set; }
        public string? Life { get; set; }
        public string? Loyalty { get; set; }
        public string? ManaCost { get; set; }
        public string? Name { get; set; }
        public string? Number { get; set; }
        public string? OriginalText { get; set; }
        public string? OriginalType { get; set; }
        public ICollection<string>? OtherFaceIds { get; set; }
        public string? Power { get; set; }
        public ICollection<string>? Printings { get; set; }
        public ICollection<string>? PromoTypes { get; set; }
        public PurchaseUrls? PurchaseUrls { get; set; }
        public string? Rarity { get; set; }
        public ICollection<Rulings>? Rulings { get; set; }
        public string? SetCode { get; set; }
        public string? Side { get; set; }
        public ICollection<string>? SubTypes { get; set; }
        public ICollection<string>? SuperTypes { get; set; }
        public string? Text { get; set; }
        public string? Toughness { get; set; }
        public string? Type { get; set; }
        public ICollection<string>? Types { get; set; }
        public ICollection<string>? Variation { get; set; }
        public string? Watermark { get; set; }
        public ICollection<Deck>? DecksContaining { get; set; }
        public Set? Set { get; set; }
        public CardPrices? LatestPrice { get; set; }
        public ICollection<CardPrices>? Prices { get; set; }
    }
}
