// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class CardImageGetInput : IGraphQlInputObject
    {
        private InputPropertyInfo _cardName;
        private InputPropertyInfo _scryfallId;
        private InputPropertyInfo _multiverseId;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? CardName
        {
            get => (QueryBuilderParameter<string?>?)_cardName.Value;
            set => _cardName = new InputPropertyInfo { Name = "cardName", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? ScryfallId
        {
            get => (QueryBuilderParameter<string?>?)_scryfallId.Value;
            set => _scryfallId = new InputPropertyInfo { Name = "scryfallId", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? MultiverseId
        {
            get => (QueryBuilderParameter<string?>?)_multiverseId.Value;
            set => _multiverseId = new InputPropertyInfo { Name = "multiverseId", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_cardName.Name != null) yield return _cardName;
            if (_scryfallId.Name != null) yield return _scryfallId;
            if (_multiverseId.Name != null) yield return _multiverseId;
        }
    }
}
