// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class CardImageQueryBuilder : GraphQlQueryBuilder<CardImageQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new GraphQlFieldMetadata { Name = "scryfallImageUrl" },
            new GraphQlFieldMetadata { Name = "multiverseImageUrl" }
        };

        protected override string TypeName { get; } = "CardImage";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get; } = AllFieldMetadata;

        public CardImageQueryBuilder WithScryfallImageUrl(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("scryfallImageUrl", alias, new GraphQlDirective?[] { include, skip });

        public CardImageQueryBuilder ExceptScryfallImageUrl() => ExceptField("scryfallImageUrl");

        public CardImageQueryBuilder WithMultiverseImageUrl(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("multiverseImageUrl", alias, new GraphQlDirective?[] { include, skip });

        public CardImageQueryBuilder ExceptMultiverseImageUrl() => ExceptField("multiverseImageUrl");
    }
}
