// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class CardPrices
    {
        public string? Id { get; set; }
        public string? Uuid { get; set; }
        public string? Format { get; set; }
        public string? Provider { get; set; }
        public string? Currency { get; set; }
        public string? Date { get; set; }
        public string? CardType { get; set; }
        public string? ListType { get; set; }
        public decimal? Price { get; set; }
    }
}
