// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class CardImageFaceInput : IGraphQlInputObject
    {
        private InputPropertyInfo _face;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<CardFace?>))]
        #endif
        public QueryBuilderParameter<CardFace?>? Face
        {
            get => (QueryBuilderParameter<CardFace?>?)_face.Value;
            set => _face = new InputPropertyInfo { Name = "face", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_face.Name != null) yield return _face;
        }
    }
}
