// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class CardToken
    {
        public string? Artist { get; set; }
        public string? AsciiName { get; set; }
        public ICollection<string>? Availability { get; set; }
        public string? BorderColor { get; set; }
        public ICollection<string>? ColorIdentity { get; set; }
        public ICollection<string>? ColorIndicator { get; set; }
        public ICollection<string>? Colors { get; set; }
        public decimal? EdhrecRank { get; set; }
        public string? FaceName { get; set; }
        public string? FlavorText { get; set; }
        public ICollection<string>? FrameEffects { get; set; }
        public string? FrameVersion { get; set; }
        public bool? HasFoil { get; set; }
        public bool? HasNonFoil { get; set; }
        public Identifier? Identifiers { get; set; }
        public bool? IsFullArt { get; set; }
        public bool? IsOnlineOnly { get; set; }
        public bool? IsPromo { get; set; }
        public bool? IsReprint { get; set; }
        public ICollection<string>? Keywords { get; set; }
        public string? Layout { get; set; }
        public string? Loyalty { get; set; }
        public string? Name { get; set; }
        public string? Number { get; set; }
        public string? Power { get; set; }
        public ICollection<string>? PromoTypes { get; set; }
        public ICollection<string>? ReverseRelated { get; set; }
        public string? SetCode { get; set; }
        public string? Side { get; set; }
        public ICollection<string>? SubTypes { get; set; }
        public string? Text { get; set; }
        public string? Toughness { get; set; }
        public string? Type { get; set; }
        public ICollection<string>? Types { get; set; }
        public string? Uuid { get; set; }
        public string? Watermark { get; set; }
    }
}
