// <auto-generated> This file has been auto generated. </auto-generated>

namespace MTGViewer.Maui.Data.MtgJson;

public partial class Deck
{
    public string? Id { get; set; }
    public string? Code { get; set; }
    public ICollection<Card>? MainBoard { get; set; }
    public string? Name { get; set; }
    public ICollection<Card>? SideBoard { get; set; }
    public string? ReleaseDate { get; set; }
    public string? Type { get; set; }
}