// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class ForeignData
    {
        public string? FaceName { get; set; }
        public string? FlavorText { get; set; }
        public string? Language { get; set; }
        public string? MultiverseId { get; set; }
        public string? Name { get; set; }
        public string? Text { get; set; }
        public string? Type { get; set; }
    }
}
