// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public static class GraphQlTypes
    {
        public const string Boolean = "Boolean";
        public const string Float = "Float";
        public const string Int = "Int";
        public const string String = "String";

        public const string BaseOperator = "BaseOperator";
        public const string CardFace = "CardFace";
        public const string LegalitiesFormat = "LegalitiesFormat";
        public const string ListOrder = "ListOrder";
        public const string ListType = "ListType";

        public const string AtomicCard = "AtomicCard";
        public const string Card = "Card";
        public const string CardImage = "CardImage";
        public const string CardPrices = "CardPrices";
        public const string CardToken = "CardToken";
        public const string Deck = "Deck";
        public const string DeckList = "DeckList";
        public const string ForeignData = "ForeignData";
        public const string Identifier = "Identifier";
        public const string LeadershipSkills = "LeadershipSkills";
        public const string Legalities = "Legalities";
        public const string Meta = "Meta";
        public const string PurchaseUrls = "PurchaseUrls";
        public const string Query = "Query";
        public const string Rulings = "Rulings";
        public const string Set = "Set";
        public const string SetList = "SetList";
        public const string Translations = "Translations";

        public const string CardCondition = "CardCondition";
        public const string CardEntityFilterInput = "CardEntityFilterInput";
        public const string CardFilter = "CardFilter";
        public const string CardImageFaceInput = "CardImageFaceInput";
        public const string CardImageGetInput = "CardImageGetInput";
        public const string DeckGetInput = "DeckGetInput";
        public const string FilterOnIdentifier = "FilterOnIdentifier";
        public const string IdentifierCondition = "IdentifierCondition";
        public const string IdentifierFilter = "IdentifierFilter";
        public const string ListOrderInput = "ListOrderInput";
        public const string PaginationInput = "PaginationInput";
        public const string PriceGetInput = "PriceGetInput";
        public const string SetGetInput = "SetGetInput";

        public static readonly IReadOnlyDictionary<Type, string> ReverseMapping =
            new Dictionary<Type, string>
            {
                { typeof(string), "String" },
                { typeof(decimal), "Float" },
                { typeof(bool), "Boolean" },
                { typeof(CardCondition), "CardCondition" },
                { typeof(CardEntityFilterInput), "CardEntityFilterInput" },
                { typeof(CardFilter), "CardFilter" },
                { typeof(CardImageFaceInput), "CardImageFaceInput" },
                { typeof(CardImageGetInput), "CardImageGetInput" },
                { typeof(DeckGetInput), "DeckGetInput" },
                { typeof(FilterOnIdentifier), "FilterOnIdentifier" },
                { typeof(IdentifierCondition), "IdentifierCondition" },
                { typeof(IdentifierFilter), "IdentifierFilter" },
                { typeof(ListOrderInput), "ListOrderInput" },
                { typeof(PaginationInput), "PaginationInput" },
                { typeof(PriceGetInput), "PriceGetInput" },
                { typeof(SetGetInput), "SetGetInput" }
            };
}
}
