// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson;

public partial class IdentifierCondition : IGraphQlInputObject
{
    private InputPropertyInfo _operator;
    private InputPropertyInfo _cardKingdomFoilIdEq;
    private InputPropertyInfo _cardKingdomFoilIdIn;
    private InputPropertyInfo _cardKingdomIdEq;
    private InputPropertyInfo _cardKingdomIdIn;
    private InputPropertyInfo _mcmIdEq;
    private InputPropertyInfo _mcmIdIn;
    private InputPropertyInfo _mcmMetaIdEq;
    private InputPropertyInfo _mcmMetaIdIn;
    private InputPropertyInfo _mtgArenaIdEq;
    private InputPropertyInfo _mtgArenaIdIn;
    private InputPropertyInfo _mtgoFoilIdEq;
    private InputPropertyInfo _mtgoFoilIdIn;
    private InputPropertyInfo _mtgoIdEq;
    private InputPropertyInfo _mtgoIdIn;
    private InputPropertyInfo _multiverseIdEq;
    private InputPropertyInfo _multiverseIdIn;
    private InputPropertyInfo _scryfallIdEq;
    private InputPropertyInfo _scryfallIdIn;
    private InputPropertyInfo _scryfallOracleIdEq;
    private InputPropertyInfo _scryfallOracleIdIn;
    private InputPropertyInfo _scryfallIllustrationIdEq;
    private InputPropertyInfo _scryfallIllustrationIdIn;
    private InputPropertyInfo _tcgplayerProductIdEq;
    private InputPropertyInfo _tcgplayerProductIdIn;

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<BaseOperator?>))]
#endif
    public QueryBuilderParameter<BaseOperator?>? Operator
    {
        get => (QueryBuilderParameter<BaseOperator?>?)_operator.Value;
        set => _operator = new InputPropertyInfo { Name = "operator", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("cardKingdomFoilId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? CardKingdomFoilIdEq
    {
        get => (QueryBuilderParameter<string?>?)_cardKingdomFoilIdEq.Value;
        set => _cardKingdomFoilIdEq = new InputPropertyInfo { Name = "cardKingdomFoilId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("cardKingdomFoilId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? CardKingdomFoilIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_cardKingdomFoilIdIn.Value;
        set => _cardKingdomFoilIdIn = new InputPropertyInfo { Name = "cardKingdomFoilId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("cardKingdomId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? CardKingdomIdEq
    {
        get => (QueryBuilderParameter<string?>?)_cardKingdomIdEq.Value;
        set => _cardKingdomIdEq = new InputPropertyInfo { Name = "cardKingdomId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("cardKingdomId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? CardKingdomIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_cardKingdomIdIn.Value;
        set => _cardKingdomIdIn = new InputPropertyInfo { Name = "cardKingdomId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mcmId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? McmIdEq
    {
        get => (QueryBuilderParameter<string?>?)_mcmIdEq.Value;
        set => _mcmIdEq = new InputPropertyInfo { Name = "mcmId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mcmId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? McmIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_mcmIdIn.Value;
        set => _mcmIdIn = new InputPropertyInfo { Name = "mcmId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mcmMetaId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? McmMetaIdEq
    {
        get => (QueryBuilderParameter<string?>?)_mcmMetaIdEq.Value;
        set => _mcmMetaIdEq = new InputPropertyInfo { Name = "mcmMetaId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mcmMetaId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? McmMetaIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_mcmMetaIdIn.Value;
        set => _mcmMetaIdIn = new InputPropertyInfo { Name = "mcmMetaId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgArenaId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? MtgArenaIdEq
    {
        get => (QueryBuilderParameter<string?>?)_mtgArenaIdEq.Value;
        set => _mtgArenaIdEq = new InputPropertyInfo { Name = "mtgArenaId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgArenaId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? MtgArenaIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_mtgArenaIdIn.Value;
        set => _mtgArenaIdIn = new InputPropertyInfo { Name = "mtgArenaId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgoFoilId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? MtgoFoilIdEq
    {
        get => (QueryBuilderParameter<string?>?)_mtgoFoilIdEq.Value;
        set => _mtgoFoilIdEq = new InputPropertyInfo { Name = "mtgoFoilId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgoFoilId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? MtgoFoilIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_mtgoFoilIdIn.Value;
        set => _mtgoFoilIdIn = new InputPropertyInfo { Name = "mtgoFoilId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgoId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? MtgoIdEq
    {
        get => (QueryBuilderParameter<string?>?)_mtgoIdEq.Value;
        set => _mtgoIdEq = new InputPropertyInfo { Name = "mtgoId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("mtgoId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? MtgoIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_mtgoIdIn.Value;
        set => _mtgoIdIn = new InputPropertyInfo { Name = "mtgoId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("multiverseId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? MultiverseIdEq
    {
        get => (QueryBuilderParameter<string?>?)_multiverseIdEq.Value;
        set => _multiverseIdEq = new InputPropertyInfo { Name = "multiverseId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("multiverseId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? MultiverseIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_multiverseIdIn.Value;
        set => _multiverseIdIn = new InputPropertyInfo { Name = "multiverseId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? ScryfallIdEq
    {
        get => (QueryBuilderParameter<string?>?)_scryfallIdEq.Value;
        set => _scryfallIdEq = new InputPropertyInfo { Name = "scryfallId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? ScryfallIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_scryfallIdIn.Value;
        set => _scryfallIdIn = new InputPropertyInfo { Name = "scryfallId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallOracleId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? ScryfallOracleIdEq
    {
        get => (QueryBuilderParameter<string?>?)_scryfallOracleIdEq.Value;
        set => _scryfallOracleIdEq = new InputPropertyInfo { Name = "scryfallOracleId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallOracleId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? ScryfallOracleIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_scryfallOracleIdIn.Value;
        set => _scryfallOracleIdIn = new InputPropertyInfo { Name = "scryfallOracleId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallIllustrationId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? ScryfallIllustrationIdEq
    {
        get => (QueryBuilderParameter<string?>?)_scryfallIllustrationIdEq.Value;
        set => _scryfallIllustrationIdEq = new InputPropertyInfo { Name = "scryfallIllustrationId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("scryfallIllustrationId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? ScryfallIllustrationIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_scryfallIllustrationIdIn.Value;
        set => _scryfallIllustrationIdIn = new InputPropertyInfo { Name = "scryfallIllustrationId_in", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("tcgplayerProductId_eq")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
#endif
    public QueryBuilderParameter<string?>? TcgplayerProductIdEq
    {
        get => (QueryBuilderParameter<string?>?)_tcgplayerProductIdEq.Value;
        set => _tcgplayerProductIdEq = new InputPropertyInfo { Name = "tcgplayerProductId_eq", Value = value };
    }

#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("tcgplayerProductId_in")]
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
#endif
    public QueryBuilderParameter<ICollection<string>?>? TcgplayerProductIdIn
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_tcgplayerProductIdIn.Value;
        set => _tcgplayerProductIdIn = new InputPropertyInfo { Name = "tcgplayerProductId_in", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_operator.Name != null) yield return _operator;
        if (_cardKingdomFoilIdEq.Name != null) yield return _cardKingdomFoilIdEq;
        if (_cardKingdomFoilIdIn.Name != null) yield return _cardKingdomFoilIdIn;
        if (_cardKingdomIdEq.Name != null) yield return _cardKingdomIdEq;
        if (_cardKingdomIdIn.Name != null) yield return _cardKingdomIdIn;
        if (_mcmIdEq.Name != null) yield return _mcmIdEq;
        if (_mcmIdIn.Name != null) yield return _mcmIdIn;
        if (_mcmMetaIdEq.Name != null) yield return _mcmMetaIdEq;
        if (_mcmMetaIdIn.Name != null) yield return _mcmMetaIdIn;
        if (_mtgArenaIdEq.Name != null) yield return _mtgArenaIdEq;
        if (_mtgArenaIdIn.Name != null) yield return _mtgArenaIdIn;
        if (_mtgoFoilIdEq.Name != null) yield return _mtgoFoilIdEq;
        if (_mtgoFoilIdIn.Name != null) yield return _mtgoFoilIdIn;
        if (_mtgoIdEq.Name != null) yield return _mtgoIdEq;
        if (_mtgoIdIn.Name != null) yield return _mtgoIdIn;
        if (_multiverseIdEq.Name != null) yield return _multiverseIdEq;
        if (_multiverseIdIn.Name != null) yield return _multiverseIdIn;
        if (_scryfallIdEq.Name != null) yield return _scryfallIdEq;
        if (_scryfallIdIn.Name != null) yield return _scryfallIdIn;
        if (_scryfallOracleIdEq.Name != null) yield return _scryfallOracleIdEq;
        if (_scryfallOracleIdIn.Name != null) yield return _scryfallOracleIdIn;
        if (_scryfallIllustrationIdEq.Name != null) yield return _scryfallIllustrationIdEq;
        if (_scryfallIllustrationIdIn.Name != null) yield return _scryfallIllustrationIdIn;
        if (_tcgplayerProductIdEq.Name != null) yield return _tcgplayerProductIdEq;
        if (_tcgplayerProductIdIn.Name != null) yield return _tcgplayerProductIdIn;
    }
}