// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class LeadershipSkillsQueryBuilder : GraphQlQueryBuilder<LeadershipSkillsQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new GraphQlFieldMetadata { Name = "brawl" },
            new GraphQlFieldMetadata { Name = "commander" },
            new GraphQlFieldMetadata { Name = "oathbreaker" }
        };

        protected override string TypeName { get; } = "LeadershipSkills";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get; } = AllFieldMetadata;

        public LeadershipSkillsQueryBuilder WithBrawl(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("brawl", alias, new GraphQlDirective?[] { include, skip });

        public LeadershipSkillsQueryBuilder ExceptBrawl() => ExceptField("brawl");

        public LeadershipSkillsQueryBuilder WithCommander(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("commander", alias, new GraphQlDirective?[] { include, skip });

        public LeadershipSkillsQueryBuilder ExceptCommander() => ExceptField("commander");

        public LeadershipSkillsQueryBuilder WithOathbreaker(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("oathbreaker", alias, new GraphQlDirective?[] { include, skip });

        public LeadershipSkillsQueryBuilder ExceptOathbreaker() => ExceptField("oathbreaker");
    }
}
