// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class MetaQueryBuilder : GraphQlQueryBuilder<MetaQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new GraphQlFieldMetadata { Name = "id" },
            new GraphQlFieldMetadata { Name = "date" },
            new GraphQlFieldMetadata { Name = "version" },
            new GraphQlFieldMetadata { Name = "dbVersion" }
        };

        protected override string TypeName { get; } = "Meta";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get; } = AllFieldMetadata;

        public MetaQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, new GraphQlDirective?[] { include, skip });

        public MetaQueryBuilder ExceptId() => ExceptField("id");

        public MetaQueryBuilder WithDate(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("date", alias, new GraphQlDirective?[] { include, skip });

        public MetaQueryBuilder ExceptDate() => ExceptField("date");

        public MetaQueryBuilder WithVersion(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("version", alias, new GraphQlDirective?[] { include, skip });

        public MetaQueryBuilder ExceptVersion() => ExceptField("version");

        public MetaQueryBuilder WithDbVersion(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("dbVersion", alias, new GraphQlDirective?[] { include, skip });

        public MetaQueryBuilder ExceptDbVersion() => ExceptField("dbVersion");
    }
}
