// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class PriceGetInput : IGraphQlInputObject
    {
        private InputPropertyInfo _uuid;
        private InputPropertyInfo _date;
        private InputPropertyInfo _format;
        private InputPropertyInfo _cardType;
        private InputPropertyInfo _listType;
        private InputPropertyInfo _provider;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Uuid
        {
            get => (QueryBuilderParameter<string?>?)_uuid.Value;
            set => _uuid = new InputPropertyInfo { Name = "uuid", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Date
        {
            get => (QueryBuilderParameter<string?>?)_date.Value;
            set => _date = new InputPropertyInfo { Name = "date", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Format
        {
            get => (QueryBuilderParameter<string?>?)_format.Value;
            set => _format = new InputPropertyInfo { Name = "format", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? CardType
        {
            get => (QueryBuilderParameter<string?>?)_cardType.Value;
            set => _cardType = new InputPropertyInfo { Name = "cardType", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? ListType
        {
            get => (QueryBuilderParameter<string?>?)_listType.Value;
            set => _listType = new InputPropertyInfo { Name = "listType", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Provider
        {
            get => (QueryBuilderParameter<string?>?)_provider.Value;
            set => _provider = new InputPropertyInfo { Name = "provider", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_uuid.Name != null) yield return _uuid;
            if (_date.Name != null) yield return _date;
            if (_format.Name != null) yield return _format;
            if (_cardType.Name != null) yield return _cardType;
            if (_listType.Name != null) yield return _listType;
            if (_provider.Name != null) yield return _provider;
        }
    }
}
