// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class PurchaseUrlsQueryBuilder : GraphQlQueryBuilder<PurchaseUrlsQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new GraphQlFieldMetadata { Name = "cardKingdom" },
            new GraphQlFieldMetadata { Name = "cardKingdomFoil" },
            new GraphQlFieldMetadata { Name = "cardmarket" },
            new GraphQlFieldMetadata { Name = "tcgplayer" }
        };

        protected override string TypeName { get; } = "PurchaseUrls";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get; } = AllFieldMetadata;

        public PurchaseUrlsQueryBuilder WithCardKingdom(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("cardKingdom", alias, new GraphQlDirective?[] { include, skip });

        public PurchaseUrlsQueryBuilder ExceptCardKingdom() => ExceptField("cardKingdom");

        public PurchaseUrlsQueryBuilder WithCardKingdomFoil(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("cardKingdomFoil", alias, new GraphQlDirective?[] { include, skip });

        public PurchaseUrlsQueryBuilder ExceptCardKingdomFoil() => ExceptField("cardKingdomFoil");

        public PurchaseUrlsQueryBuilder WithCardmarket(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("cardmarket", alias, new GraphQlDirective?[] { include, skip });

        public PurchaseUrlsQueryBuilder ExceptCardmarket() => ExceptField("cardmarket");

        public PurchaseUrlsQueryBuilder WithTcgplayer(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tcgplayer", alias, new GraphQlDirective?[] { include, skip });

        public PurchaseUrlsQueryBuilder ExceptTcgplayer() => ExceptField("tcgplayer");
    }
}
