// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class Query
    {
        public bool? Status { get; set; }
        public ICollection<Card>? Cards { get; set; }
        public CardImage? CardImage { get; set; }
        public Deck? Decks { get; set; }
        public Meta? Metadata { get; set; }
        public ICollection<CardPrices>? Prices { get; set; }
        public ICollection<Set>? Sets { get; set; }
    }
}
