// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class RulingsQueryBuilder : GraphQlQueryBuilder<RulingsQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new GraphQlFieldMetadata { Name = "date" },
            new GraphQlFieldMetadata { Name = "text" }
        };

        protected override string TypeName { get; } = "Rulings";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get; } = AllFieldMetadata;

        public RulingsQueryBuilder WithDate(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("date", alias, new GraphQlDirective?[] { include, skip });

        public RulingsQueryBuilder ExceptDate() => ExceptField("date");

        public RulingsQueryBuilder WithText(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("text", alias, new GraphQlDirective?[] { include, skip });

        public RulingsQueryBuilder ExceptText() => ExceptField("text");
    }
}
