// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class Set
    {
        public string? Id { get; set; }
        public decimal? BaseSetSize { get; set; }
        public string? Block { get; set; }
        public ICollection<Card>? Cards { get; set; }
        public string? Code { get; set; }
        public string? CodeV3 { get; set; }
        public bool? IsForeignOnly { get; set; }
        public bool? IsFoilOnly { get; set; }
        public bool? IsNonFoilOnly { get; set; }
        public bool? IsOnlineOnly { get; set; }
        public bool? IsPaperOnly { get; set; }
        public bool? IsPartialPreview { get; set; }
        public string? KeyruneCode { get; set; }
        public string? McmName { get; set; }
        public decimal? McmId { get; set; }
        public string? MtgoCode { get; set; }
        public string? Name { get; set; }
        public string? ParentCode { get; set; }
        public string? ReleaseDate { get; set; }
        public decimal? TcgplayerGroupId { get; set; }
        public ICollection<CardToken>? Tokens { get; set; }
        public decimal? TotalSetSize { get; set; }
        public Translations? Translations { get; set; }
        public string? Type { get; set; }
    }
}
