// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson
{
    public partial class SetGetInput : IGraphQlInputObject
    {
        private InputPropertyInfo _name;
        private InputPropertyInfo _code;
        private InputPropertyInfo _block;
        private InputPropertyInfo _keyruneCode;
        private InputPropertyInfo _mcmName;
        private InputPropertyInfo _mcmId;
        private InputPropertyInfo _mtgoCode;
        private InputPropertyInfo _parentCode;
        private InputPropertyInfo _releaseDate;
        private InputPropertyInfo _type;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Name
        {
            get => (QueryBuilderParameter<string?>?)_name.Value;
            set => _name = new InputPropertyInfo { Name = "name", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Code
        {
            get => (QueryBuilderParameter<string?>?)_code.Value;
            set => _code = new InputPropertyInfo { Name = "code", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Block
        {
            get => (QueryBuilderParameter<string?>?)_block.Value;
            set => _block = new InputPropertyInfo { Name = "block", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? KeyruneCode
        {
            get => (QueryBuilderParameter<string?>?)_keyruneCode.Value;
            set => _keyruneCode = new InputPropertyInfo { Name = "keyruneCode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? McmName
        {
            get => (QueryBuilderParameter<string?>?)_mcmName.Value;
            set => _mcmName = new InputPropertyInfo { Name = "mcmName", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<decimal?>))]
        #endif
        public QueryBuilderParameter<decimal?>? McmId
        {
            get => (QueryBuilderParameter<decimal?>?)_mcmId.Value;
            set => _mcmId = new InputPropertyInfo { Name = "mcmId", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? MtgoCode
        {
            get => (QueryBuilderParameter<string?>?)_mtgoCode.Value;
            set => _mtgoCode = new InputPropertyInfo { Name = "mtgoCode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? ParentCode
        {
            get => (QueryBuilderParameter<string?>?)_parentCode.Value;
            set => _parentCode = new InputPropertyInfo { Name = "parentCode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? ReleaseDate
        {
            get => (QueryBuilderParameter<string?>?)_releaseDate.Value;
            set => _releaseDate = new InputPropertyInfo { Name = "releaseDate", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
        #endif
        public QueryBuilderParameter<string?>? Type
        {
            get => (QueryBuilderParameter<string?>?)_type.Value;
            set => _type = new InputPropertyInfo { Name = "type", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_name.Name != null) yield return _name;
            if (_code.Name != null) yield return _code;
            if (_block.Name != null) yield return _block;
            if (_keyruneCode.Name != null) yield return _keyruneCode;
            if (_mcmName.Name != null) yield return _mcmName;
            if (_mcmId.Name != null) yield return _mcmId;
            if (_mtgoCode.Name != null) yield return _mtgoCode;
            if (_parentCode.Name != null) yield return _parentCode;
            if (_releaseDate.Name != null) yield return _releaseDate;
            if (_type.Name != null) yield return _type;
        }
    }
}
