// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MTGViewer.Maui.Data.MtgJson;

public partial class Translations
{
    public string? AncientGreek { get; set; }
    public string? Arabic { get; set; }
    public string? ChineseSimplified { get; set; }
    public string? ChineseTraditional { get; set; }
    public string? French { get; set; }
    public string? German { get; set; }
    public string? Hebrew { get; set; }
    public string? Italian { get; set; }
    public string? Japanese { get; set; }
    public string? Korean { get; set; }
    public string? Latin { get; set; }
    public string? Phyrexian { get; set; }
    public string? PortugueseBrazil { get; set; }
    public string? Russian { get; set; }
    public string? Sanskrit { get; set; }
    public string? Spanish { get; set; }
}