// <auto-generated> This file has been auto generated. </auto-generated>

using System.Runtime.Serialization;

namespace MTGViewer.Maui.Data.MtgJson.Enums;

public enum LegalitiesFormat
{
    [EnumMember(Value = "BRAWL")] Brawl,
    [EnumMember(Value = "COMMANDER")] Commander,
    [EnumMember(Value = "DUEL")] Duel,
    [EnumMember(Value = "FUTURE")] Future,
    [EnumMember(Value = "FRONTIER")] Frontier,
    [EnumMember(Value = "LEGACY")] Legacy,
    [EnumMember(Value = "MODERN")] Modern,
    [EnumMember(Value = "PAUPER")] Pauper,
    [EnumMember(Value = "PENNY")] Penny,
    [EnumMember(Value = "PIONEER")] Pioneer,
    [EnumMember(Value = "STANDARD")] Standard,
    [EnumMember(Value = "VINTAGE")] Vintage
}