// <auto-generated> This file has been auto generated. </auto-generated>

using System.Runtime.Serialization;

namespace MTGViewer.Maui.Data.MtgJson.Enums;

public enum ListOrder
{
    [EnumMember(Value = "ASC")] Asc,
    [EnumMember(Value = "DESC")] Desc
}