// <auto-generated> This file has been auto generated. </auto-generated>

using System.Runtime.Serialization;
namespace MTGViewer.Maui.Data.MtgJson.Enums;

public enum ListType
{
    [EnumMember(Value = "RETAIL")] Retail,
    [EnumMember(Value = "BUYLIST")] Buylist
}